import { Component, OnInit } from '@angular/core';
import { Constants as global } from 'src/app/global/constants';
@Component({
  selector: 'app-display-card',
  templateUrl: './display-card.component.html',
  styleUrls: ['./display-card.component.scss'],
})
export class DisplayCardComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.checkAnimalChoose();
    global.petInfoGlobal = this.petInfo;
  }

  petInfo = [
    {
      id: 1,
      petType: 'Dog',
      age: 3,
      date: '10/12/2020',
      tags: ['kharadi', 'kalyani nagar', 'yerwada', 'dog', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_1.jpg',
      gender: 'male',
      ownerName: 'Mohit S',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },
    {
      id: 2,
      petType: 'Cat',
      age: 4,
      date: '01/09/2020',
      tags: ['kothrud', 'kalyani nagar', 'koregaonpark', 'cat', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_1.jpg',
      gender: 'female',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Rahul sharma',
    },
    {
      id: 3,
      petType: 'Dog',
      age: 2,
      date: '10/12/2020',
      tags: ['kharadi', 'kalyani nagar', 'kothrud', 'dog', 'bron'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_2.jpg',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      gender: 'female',
      ownerName: 'Sachin P',
    },
    {
      id: 4,
      petType: 'Dog',
      age: 3,
      date: '10/12/2020',
      tags: ['kharadi', 'kothrud', 'yerwada', 'dog', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      image: '../../../assets/dog_3.jpg',
      gender: 'male',
      ownerName: 'Mango sharma',
    },
    {
      id: 5,
      petType: 'Cat',
      age: 4,
      date: '10/12/2019',
      tags: ['vadgaonsheri', 'kalyani nagar', 'yerwada', 'cat', 'brown'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      vaccinated: true,
      image: '../../../assets/cat_2.jpg',
      gender: 'female',
      ownerName: 'Avinash J',
    },
    {
      id: 6,
      petType: 'Cat',
      age: 3,
      date: '12/12/2020',
      tags: ['koregaonpark', 'kalyani nagar', 'cat', 'white'],
      spayed: true,
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_3.jpg',
      gender: 'female',
      ownerName: 'Himanshu P',
    },
    {
      id: 7,
      petType: 'Cat',
      age: 3,
      date: '10/06/2021',
      tags: ['mundhwa', 'kalyani nagar', 'hadapsar', 'cat', 'white'],
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_4.jpg',
      gender: 'male',
      ownerName: 'Baburao A',
    },
    {
      id: 8,
      petType: 'Dog',
      age: 1,
      date: '11/01/2022',
      tags: ['nigdi', 'kalyani nagar', 'yerwada', 'dog', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_4.jpg',
      gender: 'male',
      ownerName: 'Raju J',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },
    {
      id: 9,
      petType: 'Cat',
      age: 2,
      date: '27/12/2021',
      tags: ['kothrud', 'kalyani nagar', 'yerwada', 'cat', 'brown'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/cat_5.jpg',
      gender: 'female',
      ownerName: 'Mohan P',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },
    {
      id: 10,
      petType: 'Dog',
      age: 4,
      date: '11/11/2019',
      tags: ['kharadi', 'Bundgarden', 'kothrud', 'dog', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      ownerName: 'Apple apte',
      image: '../../../assets/dog_5.jpg',
      gender: 'male',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },

    {
      id: 11,
      petType: 'Dog',
      age: 3,
      date: '10/12/2020',
      tags: ['kharadi', 'kalyani nagar', 'yerwada', 'dog', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_1.jpg',
      gender: 'male',
      ownerName: 'John Doe',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },
    {
      id: 12,
      petType: 'Cat',
      age: 4,
      date: '01/09/2020',
      tags: ['kothrud', 'kalyani nagar', 'koregaonpark', 'cat', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_1.jpg',
      gender: 'female',
      ownerName: 'Mitch apte',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
    },
    {
      id: 13,
      petType: 'Dog',
      age: 2,
      date: '10/12/2020',
      tags: ['kharadi', 'kalyani nagar', 'kothrud', 'dog', 'bron'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_2.jpg',
      gender: 'female',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Reema J',
    },
    {
      id: 14,
      petType: 'Dog',
      age: 3,
      date: '10/12/2020',
      tags: ['kharadi', 'kothrud', 'yerwada', 'dog', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_3.jpg',
      gender: 'male',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Angie B',
    },
    {
      id: 15,
      petType: 'Cat',
      age: 4,
      date: '10/12/2019',
      tags: ['vadgaonsheri', 'kalyani nagar', 'yerwada', 'cat', 'brown'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/cat_2.jpg',
      gender: 'female',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Maggie D souza',
    },
    {
      id: 16,
      petType: 'Cat',
      age: 3,
      date: '12/12/2020',
      tags: ['koregaonpark', 'kalyani nagar', 'cat', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_3.jpg',
      gender: 'female',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Mohit A',
    },
    {
      id: 17,
      petType: 'Cat',
      age: 3,
      date: '10/06/2021',
      tags: ['mundhwa', 'kalyani nagar', 'hadapsar', 'cat', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: false,
      image: '../../../assets/cat_4.jpg',
      gender: 'male',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Kavita C',
    },
    {
      id: 18,
      petType: 'Dog',
      age: 1,
      date: '11/01/2022',
      tags: ['nigdi', 'kalyani nagar', 'yerwada', 'dog', 'white'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_4.jpg',
      gender: 'male',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Ruth C',
    },
    {
      id: 19,
      petType: 'Cat',
      age: 2,
      date: '27/12/2021',
      tags: ['kothrud', 'kalyani nagar', 'yerwada', 'cat', 'brown'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/cat_5.jpg',
      gender: 'female',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Ira C',
    },
    {
      id: 20,
      petType: 'Dog',
      age: 4,
      date: '11/11/2019',
      tags: ['kharadi', 'Bundgarden', 'kothrud', 'dog', 'black'],
      spayed: true,
      vaccination: ['rabies', 'Distemper', 'Leptospirosis', 'Parvovirus'],
      vaccinated: true,
      image: '../../../assets/dog_5.jpg',
      gender: 'male',
      phoneNumber: 9988776654,
      email: 'sharmarahul@gmail.com',
      ownerName: 'Chintu kumar',
    },
  ];

  petInfoSpecific: any[] = [];

  checkAnimalChoose() {
    for (let i = 0; i <= this.petInfo.length - 1; i++) {
      if (global.animalchoosed === 'cat') {
        console.log('object', this.petInfo[i].gender);
        let temp = this.petInfo[i].petType;
        console.log(temp);
        if (temp === 'Cat') {
          console.log('hehe', this.petInfo[i].petType);
          this.petInfoSpecific = [
            ...this.petInfoSpecific,
            {
              id: this.petInfo[i].id,
              petType: this.petInfo[i].petType,
              gender: this.petInfo[i].gender,
              spayed: this.petInfo[i].spayed,
              vaccinated: this.petInfo[i].vaccinated,
              image: this.petInfo[i].image,
            },
          ];
          console.log('hello', this.petInfoSpecific[0].petType);
        }
      } else if (global.animalchoosed === 'dog') {
        let temp = this.petInfo[i].petType;
        console.log(temp);
        if (temp === 'Dog') {
          console.log('hehe', this.petInfo[i].petType);
          this.petInfoSpecific = [
            ...this.petInfoSpecific,
            {
              id: this.petInfo[i].id,
              petType: this.petInfo[i].petType,
              gender: this.petInfo[i].gender,
              spayed: this.petInfo[i].spayed,
              vaccinated: this.petInfo[i].vaccinated,
              image: this.petInfo[i].image,
            },
          ];
          console.log('hello', this.petInfoSpecific[0].petType);
        }
      } else {
        this.petInfoSpecific = this.petInfo;
      }
    }
  }
}
